- type: job
  id: TraumaParamedic
  name: job-name-traumaparamedic
  description: job-description-traumaparamedic
  playTimeTracker: JobTraumaParamedic
  whitelisted: true
  startingGear: TraumaParamedicGear
  alwaysUseSpawner: true
  icon: "JobIconDoc"
  supervisors: job-supervisors-trauma-repr
  weight: 170
  canBeAntag: false
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: TraumaParamedicGear
  equipment:
    id: TraumaParamedicIDCard
    pocket1: EncryptionKeyTrauma
    pocket2: PinpointerUniversal
    jumpsuit: ClothingUniformJumpsuitMilitaryColorGrey
    shoes: ClothingShoesSwat
