when:
  - event: [ manual ]

steps:
  - name: build Content.Packaging
    image: "localhost/dotnet-sdk:9.0.201"
    commands:
      - dotnet build Content.Packaging --configuration Release --property WarningLevel=0

  - name: run Content.Packaging
    image: "localhost/dotnet-sdk:9.0.201"
    commands:
      - dotnet run --project Content.Packaging server --platform linux-x64 --hybrid-acz --property WarningLevel=0

  - name: storage Content.Server
    image: "debian:bookworm"
    volumes:
      - "/var/lib/star-horizon/woodpecker/storage:/storage"
    commands:
      - bash -c 'if [[ ! -e /storage/ss14/${CI_COMMIT_BRANCH} ]]; then mkdir -p /storage/ss14/${CI_COMMIT_BRANCH}; fi'
      - mv release/SS14.Server_linux-x64.zip /storage/ss14/${CI_COMMIT_BRANCH}/
      - cp Resources/ConfigPresets/StarHorizon/server_config.toml /storage/ss14/${CI_COMMIT_BRANCH}/
      - echo '${CI_COMMIT_SHA}' > /storage/ss14/${CI_COMMIT_BRANCH}/build_commit.txt
